/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        int i = 2;
  if(n < 2) return false;
  else if(i >=2){ 
    while(i <= Math.sqrt(n)){
        if(n % i == 0){
       return false; }
    i++;
   } 
  }
  return true;
    }
    public long firstPrimeNumberIn(String n) {
        // Write your code here.
        return -1;
    }
}
